const STAGYON_PRODUCTS = [
  // ---- DELL ----
  { id: "sg-001", brand: "Dell", model: "Dell Latitude 5289", cpu: "Intel Core i7 (7th Gen)", ram: "8GB", storage: "256GB SSD", screen: "12.5\" FHD Touch", category: "business", tags: ["2-in-1", "business", "dell"], price: 900000, qty: 1, image: "dell5289.webp" },
  { id: "sg-002", brand: "Dell", model: "Dell XPS 13 7390", cpu: "Intel Core i7 (10th Gen)", ram: "16GB", storage: "512GB SSD", screen: "13.3\" FHD", category: "ultrabook", tags: ["ultrabook", "premium", "dell"], price: 2400000, qty: 1, image: "xps1.jpeg" },
  { id: "sg-003", brand: "Dell", model: "Dell Inspiron 16 5643", cpu: "AMD Ryzen 7", ram: "16GB", storage: "512GB SSD", screen: "16\" FHD", category: "mainstream", tags: ["mainstream", "dell", "ryzen"], price: 1550000, qty: 1, image: "inspiron.jpg" },
  { id: "sg-004", brand: "Dell", model: "Dell Latitude 5300", cpu: "Intel Core i5 (8th Gen)", ram: "8GB", storage: "256GB SSD", screen: "13.3\" FHD", category: "business", tags: ["business", "dell"], price: 950000, qty: 1, image: "5300.webp" },
  { id: "sg-005", brand: "Dell", model: "Dell Inspiron 14 5410", cpu: "Intel Core i3 (11th Gen)", ram: "8GB", storage: "256GB SSD", screen: "14\" FHD", category: "budget", tags: ["budget", "dell"], price: 750000, qty: 0, image: "inspiron14.jpg" },
  { id: "sg-006", brand: "Dell", model: "Dell Inspiron 16", cpu: "AMD Ryzen 7", ram: "16GB", storage: "512GB SSD", screen: "16\" FHD", category: "mainstream", tags: ["mainstream", "dell", "ryzen"], price: 1550000, qty: 0, image: "inspo16.jpg" },
  // ---- HP ----
  { id: "sg-007", brand: "HP", model: "HP OMEN Gaming Laptop 16", cpu: "AMD Ryzen 7 AI", ram: "16GB", storage: "512GB SSD", screen: "16\" FHD 144Hz", gpu: "RTX 4050", category: "gaming", tags: ["gaming", "hp", "omen", "ryzen"], price: 2900000, qty: 0, image: "omen7ai.jpg" },
  { id: "sg-008", brand: "HP", model: "HP Pavilion x360 2-in-1 14", cpu: "Intel Core 7 (13th Gen)", ram: "16GB", storage: "512GB SSD", screen: "14\" FHD Touch", category: "2in1", tags: ["2-in-1", "hp", "pavilion"], price: 1700000, qty: 1, image: "pavillion.webp" },
  { id: "sg-009", brand: "HP", model: "HP Victus 15", cpu: "Intel Core i5 (13th Gen)", ram: "8GB", storage: "512GB SSD", screen: "15.6\" FHD 144Hz", gpu: "RTX 2050", category: "gaming", tags: ["gaming", "hp", "victus"], price: 3300000, qty: 1, image: "victus1.jpg" },
  { id: "sg-010", brand: "HP", model: "HP OMEN Transcend 14", cpu: "Intel Core Ultra 7", ram: "32GB", storage: "1TB SSD", screen: "14\" 3K OLED", gpu: "RTX Laptop GPU", category: "gaming", tags: ["gaming", "premium", "hp", "omen"], price: 4200000, qty: 1, image: "omentrans.webp" },
  { id: "sg-011", brand: "HP", model: "HP OMEN 16", cpu: "Intel Core i5 (14th Gen)", ram: "16GB", storage: "512GB SSD", screen: "16\" FHD 144Hz", gpu: "RTX 4060", category: "gaming", tags: ["gaming", "hp", "omen"], price: 3300000, qty: 1, image: "omen33.jpg" },
  { id: "sg-012", brand: "HP", model: "HP OMEN 16", cpu: "AMD Ryzen 9 AI", ram: "16GB", storage: "1TB SSD", screen: "16\" QHD 165Hz", gpu: "RTX 4070", category: "gaming", tags: ["gaming", "hp", "omen", "ryzen"], price: 4600000, qty: 1, image: "omen216.avif" },
  { id: "sg-013", brand: "HP", model: "HP OmniBook Ultra 14", cpu: "AMD Ryzen 9 AI", ram: "32GB", storage: "1TB SSD", screen: "14\" 2.8K OLED", category: "ultrabook", tags: ["ultrabook", "premium", "hp", "omnibook"], price: 3600000, qty: 1, image: "omniultra.webp" },
  { id: "sg-014", brand: "HP", model: "HP OMEN 16", cpu: "AMD Ryzen 9", ram: "16GB", storage: "512GB SSD", screen: "16\" FHD 144Hz", gpu: "RTX 4060", category: "gaming", tags: ["gaming", "hp", "omen", "ryzen"], price: 3200000, qty: 1, image: "omen44.jpg" },
  { id: "sg-015", brand: "HP", model: "HP OMEN 16", cpu: "Intel Core i7 (14th Gen)", ram: "16GB", storage: "1TB SSD", screen: "16\" QHD 165Hz", gpu: "RTX 4070", category: "gaming", tags: ["gaming", "hp", "omen"], price: 4700000, qty: 0, image: "omen55.jpg" },
  { id: "sg-016", brand: "HP", model: "HP Envy x360 14", cpu: "AMD Ryzen 5", ram: "16GB", storage: "512GB SSD", screen: "14\" 2.8K OLED Touch", category: "2in1", tags: ["2-in-1", "hp", "envy", "ryzen"], price: 2200000, qty: 1, image: "envy14.webp" },
  { id: "sg-017", brand: "HP", model: "HP EliteBook G1q", cpu: "Snapdragon (ARM)", ram: "16GB", storage: "512GB SSD", screen: "14\" FHD", category: "business", tags: ["business", "hp", "elitebook"], price: 1900000, qty: 1, image: "snapd.webp" },
  { id: "sg-018", brand: "HP", model: "HP OmniBook 5 15", cpu: "AMD Ryzen AI", ram: "16GB", storage: "512GB SSD", screen: "15.6\" FHD", category: "mainstream", tags: ["mainstream", "hp", "omnibook", "ryzen"], price: 1600000, qty: 1, image: "omni5.jfif" },
  { id: "sg-019", brand: "HP", model: "HP EliteBook 840 G7", cpu: "Intel Core i7 (10th Gen)", ram: "16GB", storage: "512GB SSD", screen: "14\" FHD", category: "business", tags: ["business", "hp", "elitebook"], price: 2000000, qty: 3, image: "840g7.avif" },
  { id: "sg-020", brand: "HP", model: "HP EliteBook 830 G8", cpu: "Intel Core i5 (11th Gen)", ram: "8GB", storage: "256GB SSD", screen: "13.3\" FHD", category: "business", tags: ["business", "hp", "elitebook"], price: 1500000, qty: 1, image: "830g8.avif" },
  { id: "sg-021", brand: "HP", model: "HP OmniBook X Flip 14", cpu: "AMD Ryzen 5 AI", ram: "16GB", storage: "512GB SSD", screen: "14\" 2K Touch", category: "2in1", tags: ["2-in-1", "hp", "omnibook", "ryzen"], price: 2000000, qty: 1, image: "xflip.jpg" },
  { id: "sg-022", brand: "HP", model: "HP EliteBook 830 G8", cpu: "Intel Core i7 (11th Gen)", ram: "16GB", storage: "512GB SSD", screen: "13.3\" FHD", category: "business", tags: ["business", "hp", "elitebook"], price: 2000000, qty: 1, image: "830g8.avif" },
  { id: "sg-023", brand: "HP", model: "HP EliteBook 830 G11", cpu: "Intel Core Ultra 5", ram: "16GB", storage: "512GB SSD", screen: "13.3\" FHD", category: "business", tags: ["business", "hp", "elitebook", "premium"], price: 2800000, qty: 2, image: "830g11.jpg" },
  { id: "sg-024", brand: "HP", model: "HP EliteBook x360 830 G7", cpu: "Intel Core i5 (10th Gen)", ram: "8GB", storage: "256GB SSD", screen: "13.3\" FHD Touch", category: "2in1", tags: ["2-in-1", "business", "hp", "elitebook"], price: 1600000, qty: 1, image: "g7x360.png" },
  { id: "sg-025", brand: "HP", model: "HP EliteBook 1040 G7", cpu: "Intel Core i7 (10th Gen)", ram: "16GB", storage: "512GB SSD", screen: "14\" FHD", category: "business", tags: ["business", "premium", "hp", "elitebook"], price: 2300000, qty: 2, image: "1040g7.webp" },
  { id: "sg-026", brand: "HP", model: "HP OmniBook X Flip", cpu: "Intel Core Ultra 7", ram: "32GB", storage: "1TB SSD", screen: "14\" 2.8K OLED Touch", category: "2in1", tags: ["2-in-1", "premium", "hp", "omnibook"], price: 3400000, qty: 1, image: "omnix2.avif" },
  { id: "sg-027", brand: "HP", model: "HP OmniBook 5 Flip", cpu: "Intel Core 5", ram: "16GB", storage: "512GB SSD", screen: "14\" FHD Touch", category: "2in1", tags: ["2-in-1", "hp", "omnibook"], price: 1900000, qty: 1, image: "omnibook5.jfif" },
  { id: "sg-028", brand: "HP", model: "HP Envy x360 15", cpu: "Intel Core Ultra 7", ram: "16GB", storage: "512GB SSD", screen: "15.6\" FHD Touch", category: "2in1", tags: ["2-in-1", "hp", "envy"], price: 2600000, qty: 0, image: "envy15.jpg" },
  { id: "sg-029", brand: "HP", model: "HP Spectre 16", cpu: "Intel Core i7 (12th Gen)", ram: "16GB", storage: "1TB SSD", screen: "16\" 3K2K OLED Touch", category: "ultrabook", tags: ["ultrabook", "premium", "hp", "spectre"], price: 3400000, qty: 1, image: "spectre16.webp" },
  { id: "sg-030", brand: "HP", model: "HP 14", cpu: "Intel Pentium", ram: "4GB", storage: "128GB SSD", screen: "14\" HD", category: "budget", tags: ["budget", "hp"], price: 480000, qty: 2, image: "hp14.jpg" },
  { id: "sg-031", brand: "HP", model: "HP 440", cpu: "Intel Pentium", ram: "4GB", storage: "500GB HDD", screen: "14\" HD", category: "budget", tags: ["budget", "hp"], price: 450000, qty: 1, image: "probook440.jpg" },
  { id: "sg-032", brand: "HP", model: "HP 840 G4", cpu: "Intel Core i7 (7th Gen)", ram: "8GB", storage: "256GB SSD", screen: "14\" FHD", category: "business", tags: ["business", "hp", "elitebook"], price: 850000, qty: 1, image: "840g4.jpg" },
  { id: "sg-033", brand: "HP", model: "HP 14", cpu: "Intel Celeron", ram: "4GB", storage: "128GB eMMC", screen: "14\" HD", category: "budget", tags: ["budget", "hp"], price: 420000, qty: 2, image: "hp142.webp" },
  { id: "sg-034", brand: "HP", model: "HP OMEN 16", cpu: "Intel Core i7 (11th Gen)", ram: "16GB", storage: "512GB SSD", screen: "16\" FHD 144Hz", gpu: "RTX 3060", category: "gaming", tags: ["gaming", "hp", "omen"], price: 2700000, qty: 0, image: "omen11th.jfif" },
  { id: "sg-035", brand: "HP", model: "HP ZBook Firefly 15", cpu: "Intel Core i7 (11th Gen)", ram: "16GB", storage: "512GB SSD", screen: "15.6\" FHD", category: "workstation", tags: ["workstation", "business", "hp", "zbook"], price: 2400000, qty: 0, image: "zbook.webp" },
  // ---- LENOVO ----
  { id: "sg-036", brand: "Lenovo", model: "Lenovo ThinkPad T14", cpu: "AMD Ryzen 7", ram: "16GB", storage: "512GB SSD", screen: "14\" FHD", category: "business", tags: ["business", "lenovo", "thinkpad", "ryzen"], price: 1900000, qty: 1, image: "t14.jpg" },
  { id: "sg-037", brand: "Lenovo", model: "Lenovo ThinkBook 14 G4", cpu: "Intel Core i7 (11th Gen)", ram: "16GB", storage: "512GB SSD", screen: "14\" FHD", category: "business", tags: ["business", "lenovo", "thinkbook"], price: 1800000, qty: 1, image: "thinkbook.jfif" },
  { id: "sg-038", brand: "Lenovo", model: "Lenovo ThinkPad X1 Carbon", cpu: "Intel Core i5 (8th Gen)", ram: "8GB", storage: "256GB SSD", screen: "14\" FHD", category: "business", tags: ["business", "premium", "lenovo", "thinkpad"], price: 1300000, qty: 0, image: "x18th.jfif" },
  { id: "sg-039", brand: "Lenovo", model: "Lenovo ThinkPad 11e Yoga (3rd Gen)", cpu: "Intel Celeron (8th Gen)", ram: "4GB", storage: "128GB SSD", screen: "11.6\" HD Touch", category: "budget", tags: ["budget", "2-in-1", "lenovo", "thinkpad"], price: 500000, qty: 4, image: "lenovo11e.jfif" },
  { id: "sg-040", brand: "Lenovo", model: "Lenovo ThinkPad X1 Carbon", cpu: "Intel Core i7 (6th Gen)", ram: "8GB", storage: "256GB SSD", screen: "14\" FHD", category: "business", tags: ["business", "premium", "lenovo", "thinkpad"], price: 1100000, qty: 1, image: "x16th.jpg" },
  { id: "sg-041", brand: "Lenovo", model: "Lenovo ThinkPad X1 Carbon", cpu: "Intel Core i7 (10th Gen)", ram: "16GB", storage: "512GB SSD", screen: "14\" FHD", category: "business", tags: ["business", "premium", "lenovo", "thinkpad"], price: 2000000, qty: 2, image: "x110th.avif" },
  { id: "sg-042", brand: "Lenovo", model: "Lenovo ThinkPad X1 Carbon", cpu: "Intel Core Ultra 7", ram: "32GB", storage: "1TB SSD", screen: "14\" 2.8K OLED", category: "business", tags: ["business", "premium", "lenovo", "thinkpad"], price: 3700000, qty: 0, image: "x114th.webp" },
  { id: "sg-043", brand: "Lenovo", model: "Lenovo ThinkPad X1 Nano", cpu: "Intel Core i7 (11th Gen)", ram: "16GB", storage: "512GB SSD", screen: "13\" 2K", category: "ultralight", tags: ["ultralight", "premium", "lenovo", "thinkpad"], price: 2500000, qty: 1, image: "nano.jpg" },
  // ---- APPLE ----
  { id: "sg-044", brand: "Apple", model: "MacBook Air (2020)", cpu: "Apple Core i5", ram: "8GB", storage: "256GB SSD", screen: "13.3\" Retina", category: "apple", tags: ["apple", "macbook", "ultrabook"], price: 3000000, qty: 1, image: "macair2020.jpg" },
  // ---- ACER ----
  { id: "sg-045", brand: "Acer", model: "Acer Aspire 3 15", cpu: "AMD Ryzen 3", ram: "8GB", storage: "256GB SSD", screen: "15.6\" FHD", category: "budget", tags: ["budget", "acer", "ryzen"], price: 850000, qty: 1, image: "accer.webp" },
  // ---- HUAWEI ----
  { id: "sg-046", brand: "Huawei", model: "Huawei MateBook E", cpu: "Intel Core i5", ram: "8GB", storage: "256GB SSD", screen: "12\" 2K Touch", category: "ultralight", tags: ["ultralight", "huawei", "2-in-1"], price: 1450000, qty: 1, image: "matebooke.jpg" },
];

const CATEGORY_LABELS = {
  gaming: "Gaming",
  business: "Business",
  ultrabook: "Ultrabook",
  "2in1": "2 in 1",
  budget: "Budget",
  apple: "Apple",
  workstation: "Workstation",
  ultralight: "Ultralight",
  mainstream: "Everyday",
};